server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-simulator
  
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/simulator}
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.simulator: DEBUG
    com.github.tomakehurst.wiremock: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

simulator:
  active-dataset: ${ACTIVE_DATASET:default}
  auth:
    enabled: ${AUTH_ENABLED:false}
  wiremock:
    port: 9999
    admin-port: 9998